# Generated by Django 5.0.4 on 2024-05-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('pprice', models.IntegerField(blank=True, null=True)),
                ('pdescription', models.CharField(blank=True, max_length=100, null=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
