# Generated by Django 5.0.6 on 2024-05-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_register_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_db',
            name='cpassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
