# Generated by Django 5.0.6 on 2024-05-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_register_db_cpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_db',
            name='cpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register_db',
            name='remail',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register_db',
            name='rname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register_db',
            name='rpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
